name: "Deploy website to github.io"
run-name: "Deploy website Run: ${{ github.run_id }}"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
    paths:
      - "forntend/*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-static-website:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build site
        env:
          CI: false # in order not to treat warning as errors. CI = true will treat warning as erros which is the default.
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "frontend/build/*"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
